# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'my-project'

        #rule_files:
        #  #  - 'alert.rules'
        #  # - "first.rules"
        #  # - "second.rules"

# alert
#alerting:
#  alertmanagers:
#  - scheme: http
#    static_configs:
#    - targets:
#      - "alertmanager.prom:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: 'prometheus'
    static_configs:
         - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - 'cadvisor.prom'
      type: 'A'
      port: 8080

  - job_name: 'gitea'
    dns_sd_configs:
    - names:
      - 'gitea'
      type: 'A'
      port: 3000

  - job_name: 'node-exporter'
    dns_sd_configs:
    - names:
      - 'node-exporter.prom'
      type: 'A'
      port: 9100

    relabel_configs:
      - source_labels: [instance]
        target_label: __tmp_instance
        regex: '(.+)'
        replacement: '${1};'
      - source_labels: [__tmp_instance, __address__]
        separator: ''
        target_label: instance
        regex: '([^:;]+)((:[0-9]+)?|;(.*))'
        replacement: '${1}'

  - job_name: 'traefik'
    static_configs:
    - targets: ['traefik.prom:8080']
